### ISSUE TITLE
Fatal Error caused by Plugin 

### ISSUE THREAD

**Issue by StrategyLLC** [spinupwp/spinupwp-plugin#61]
Hey Everyone, I had the plugin throw a fatal error on my site, causing the whole site to go down, does anyone know what may have caused this, or have a solution to it. For now I have just disabled the plugin entirely.

The error log is below:

[31-Aug-2022 15:50:06 UTC] PHP Fatal error: Uncaught Error: Class 'SpinupWp\Plugin' not found in /sites/---SITENAME---/files/wp-content/plugins/spinupwp/spinupwp.php:45

Stack trace:
#0 /sites/---SITENAME---/files/wp-content/plugins/spinupwp/spinupwp.php(51): spinupwp()
#1 /sites/---SITENAME---/files/wp-settings.php(428): include_once('/sites/---SITENAME---...')
#2 /sites/---SITENAME---/files/wp-config.php(88): require_once('/sites/---SITENAME---...')
#3 /sites/---SITENAME---/files/wp-load.php(50): require_once('/sites/---SITENAME---...')
#4 /sites/---SITENAME---/files/wp-blog-header.php(13): require_once('/sites/---SITENAME---...')
#5 /sites/---SITENAME---/files/index.php(17): require('/sites/---SITENAME---...')
#6 {main}
thrown in /sites/---SITENAME---/files/wp-content/plugins/spinupwp/spinupwp.php on line 45

**Comment by A5hleyRich** [comment]
Sorry that you ran into this issue. We had a problem with our plugin release process that caused this error. Deleting and re-installing the plugin will resolve the error.
