### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function get() on null in object-cache.php:194

### ISSUE THREAD

**Issue by mattneal-stafflink** [spinupwp/spinupwp-plugin#80]
Plugin Version: 1.6
PHP Version: 8.0.30
WordPress Version: 6.5.2

The issue happens when I try activating the plugin. The site cannot load at all, unless I remove the `object-cache.php` file from `files/web/app`.

Full Stack Trace:

```
#0 /sites/websitename.com.au/files/web/wp/wp-includes/class-wp-textdomain-registry.php(187): wp_cache_get()
#1 /sites/websitename.com.au/files/web/wp/wp-includes/class-wp-textdomain-registry.php(302): WP_Textdomain_Registry->get_language_files_from_path()
#2 /sites/websitename.com.au/files/web/wp/wp-includes/class-wp-textdomain-registry.php(98): WP_Textdomain_Registry->get_path_from_lang_dir()
#3 /sites/websitename.com.au/files/web/wp/wp-includes/l10n.php(1354): WP_Textdomain_Registry->get()
#4 /sites/websitename.com.au/files/web/wp/wp-includes/l10n.php(1384): _load_textdomain_just_in_time()
#5 /sites/websitename.com.au/files/web/wp/wp-includes/l10n.php(194): get_translations_for_domain()
#6 /sites/websitename.com.au/files/web/wp/wp-includes/l10n.php(306): translate()
#7 /sites/websitename.com.au/files/web/app/object-cache.php(2925): __()
#8 /sites/websitename.com.au/files/web/app/object-cache.php(2897): WP_Object_Cache->show_error_and_die()
#9 /sites/websitename.com.au/files/web/app/object-cache.php(577): WP_Object_Cache->handle_exception()
#10 /sites/websitename.com.au/files/web/app/object-cache.php(247): WP_Object_Cache->__construct()
#11 /sites/websitename.com.au/files/web/wp/wp-includes/load.php(860): wp_cache_init()
#12 /sites/websitename.com.au/files/web/wp/wp-settings.php(144): wp_start_object_cache()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1363): require('...')
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1282): WP_CLI\Runner->load_wordpress()
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process()
#17 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#18 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('...')
#19 /usr/local/bin/wp(4): include('...')
#20 {main}
  thrown in /sites/websitename.com.au/files/web/app/object-cache.php on line 194
```

The issue appears to be that the global `$WP_Object_Cache` is returning null. I'm stuck at this point, as this isn't happening on other sites, however, I don't believe this is site specific. Most likely a server config?

**Comment by Jamesclark32** [comment]
Hey @mattneal-stafflink, I've been unable to reproduce this error thus far. Would you mind writing us in support sudo@spinupwp.com so we can dig into this a bit deeper?

**Comment by mattneal-stafflink** [comment]
Thanks @Jamesclark32, I can't recreate it on any of our other sites so for now I'm going to write this off as a site specific/theme problem. Most likely has something to do with the theme or something else.

I'm gonna turn a blind eye to it and hope I don't run into it again 🤣

**Comment by Jamesclark32** [comment]
Glad to hear it's resolved! If you do encounter it again, don't hesitate to let us know.
